# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-19 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authur',
            new_name='author',
        ),
    ]
